### ISSUE TITLE
Cart: Add cart modal

### ISSUE THREAD

**Issue by stackus** [boozallen/projectjellyfish#1063]
Belongs To #1061 

The cart modal makes a return. Most of it can be salvaged from the git history. Some major differences be added, namely the configuring of products. The cart navigation item should also be brought back, it also can be salvaged from the git history.

The cart will need to be updated to support the new, new to the old cart, features from #1061.

Also,
- Ordering needs to be removed from it's new home and put back into the cart.
- Answering the `service_questions` must happen in some way in the cart.

***Working Branch:*** https://github.com/projectjellyfish/api/compare/master...AllenBW:enhancement_1063

**Comment by AllenBW** [comment]
A quick question with respect to answering service questions, going to calling this "configuration".  Should the configuration  occur prior to or after purchasing the contents of a cart?  First instinct on ordering workflow detailed below, this is working off the assumption we only have products as they relate to one project in the cart at a time.

1. From marketplace, a user adds services to "Compare", the button at the of the bottom of the compare table reads "Configure".
2. User selects "Configure" for a service, is prompted to select a project (if not previously been selected, or the user's origin is not project.details) and answer configuration questions. Upon completion user selects "Add To Cart".
3. Product is added to cart and the cart now has a Project set, all other products added will be against this project ("Clear/Reset Cart" could be an button to quickly remove all services). The cart, in addition to displaying the current products (each of which will show a remove action), will display the change in monthly costs and relevant budget warnings.
4.  In the cart selecting "Order Products" will display list previewing of each products' present configuration (also provide the option to reconfigure each if desired),and a "Confirm Order" button, which upon selection will add the products to the project and the cart will be cleared.


Second workflow instinct is below, products grouped by multiple projects in the cart (does away with aforementioned assumption):

1. From marketplace, a user adds services to compare, the button at the of the bottom of the compare table reads "Add to Cart".
2. "Add to Cart" reveals a modal that prompts the user to select a  project under which to add the product (this happens each time).
3. Product shows up in the cart under a "Project Tab" each new project will add an additional tab. In addition to the products list (which will show a remove action), will display the change in monthly costs and budget warnings  will be displayed in a project tab.  
4. Prom the "Project Tab" the button "Configure Project Products" upon selection, will take the user to a configuration page wherein the configuration required for each product is listed. After entering all required fields for each product requiring configuration, the user may select  "Order Products".  And so they will be added to the project and the "Project Tab" will be removed. And there will be much rejoicing.

**Comment by sonejah21** [comment]
Great job in laying the thought process out here. 

I lean toward the 2nd workflow you mention above (aka: products grouped by multiple projects in the cart). A cart shall contain all of the things you want, even if they aren't for the same project. It may look slightly less sleek - having multiple "tabs" in the cart -but I think it is more intuitive to have a cart that doesn't restrict you to one project at a time (if I understand that right).

**Comment by stackus** [comment]
A user can add multiple 'copies' of a product to their order. These copies could all be on a single project or be across several projects. Orders will be made a a project group level.

*You suggest having a page for the cart in your second option, and if it makes getting all of the below working easier than having a cart modal, that works for me.*

The cart should have a helper/extra-ness to pick and set a project. The following is what I envision for the two flows. (From the marketplace, and from 'add services' on a project)

User is browsing the marketplace.
1. Clicks 'order' somewhere for a product, this can be either the order button in the compare dialog or a 'cart' icon on the product row.
2. If the cart has not had a 'chosen project' set then a 'project selection' modal is displayed. The modal has a listing of available projects and a checkbox to 'remember this choice'.
3. Product is put into the cart under the chosen project.

User clicks 'add service' from a project
1. The 'chosen project' is set on arrival to the marketplace.
2. Adding products does not bring up a project selection modal.

Couple additional things
- The chosen project should be held in the carts service state, it's not a value held in the marketplace or elsewhere.
- The chosen project should be clearable by the user. Adding something to the cart modal to allow this seems like a good place.

As for configuring the products. This *must* happen before the product is ordered. Two ideas
- Combine the project modal with the settings form. The 'chosen project' would now be the default choice for the selection and there would be no need to allow the user to clear it.
  - Downsides here is the user has to answer all of the questions before adding the project to the cart to see their costs.
- Use the sprocket icon on each product row in the cart that would display the settings the user would need to set.
  - The settings could appear in an expandable space, or the cart modal could change into a configuration view for the product.
  - After a product has been configured some sort of visual cue is needed so the user knows which they have already configured

Products cannot be allowed to be ordered without being configured first. So this means an entire project is locked down until all products are taken care of.

**Comment by voxlol** [comment]
Maybe I don't completely understand the cart, but I don't think the user should have to order a product from the Compare modal? If the user already knows which item they want, I think it'd be more streamlined to skip the Compare modal by having an Add to Cart button somewhere in the Marketplace (if possible).

I agree with Sonja that allowing for grouping by different projects in the cart is preferable. I think it's better to go with the less restrictive option just in case. Also, I think products should definitely be configured before being ordered. 

Great work!

**Comment by mafernando** [comment]
Sorry for the belated reply here (was moving tables earlier), but I think my thoughts align with Sonja's in this instance.

- Users should be able to have a multi-project cart. Someone will want to go in and shop for multiple products that will be mapped to different projects sooner or later.

- Users should be asked to configure the product prior to adding it to the cart. This is a bit tricky since those configuration options would have to be managed in the browser. 
  - The current marketplace implementation avoids this as you are guided to configure and add/purchase only one product at a time, so persisting configuration metatdata isn't an issue.
 - Doing this is important because modules have the ability to define questions that get asked when a user "instantiates" a marketplace product into a project. The answers to these questions will need to be persisted somewhere if we are doing multi-product/project carts.

Other thoughts:

- _From marketplace, a user adds services to compare, the button at the of the bottom of the compare table reads "Add to Cart"._ - I'm thinking that users don't want to add all the services that they are comparing, only a single one. So adding all services from those currently being compared doesn't quite make sense to me. 

- Perhaps a hybrid approach could be:
  1) user clicks the cog in the current marketplace to trigger a product/project order configuration modal
  2) user (in that modal) configures the product to align against a specified project and clicks a confirm button, e.g. 'Complete Product Order Config' - but shorter ;)
  3) user is returned to the marketplace and can see in their cart that the product has been added to the current order (the orders config is persisted in the browser somewhere)
  4\*) user repeats 1 - 3 for other projects 
  5) user then clicks the cart icon to open up the cart modal and then clicks a  'purchase' button to actually add those products to their respective projects as well as kick-off any necessary provisioning steps ** this could get tricky if the modules need to be configured with each other, ask me if you're curious on how this could play out**

Great work so far!

**Comment by mafernando** [comment]
Pricing -> Configuration -> Booking ftw!

**Comment by AllenBW** [comment]
Thanks all for the feedback!  Most appreciated, definitely enough to get me rolling. After a solid conversation with @mafernando breaking down the process of adding a product to a project into the following stages:

* Pricing - adding a product to the cart - Designed to be as streamlined as possible, all products are added to the cart so long as a project is specified (by either origin of state or specified by the user). Initially, estimate prices are displayed when available.  Some products will require configuration prior to final pricing and will be indicated as such.
* Configuring - answer product questions related to a product - Performed via a transformation of the cart modal, until completed for each item requiring, incomplete product configuration  prohibits purchasing the cart contents on that the specific project tab.
* Ordering - adding  products as services to a project - To a user, the simple action of reviewing final purchase details and adding the specified services with their configuration to the relevant project.  Products on a project cannot be ordered until all projects are configured.

The above narrative will be completed by fleshing out the following tasks:

Marketplace
* cart icon will be added to the actions column for each product, will require user to specify project when before adding to the cart unless a default project has been specified

 Working-project Helper
* dictated by user origin (marketplace or project details) this will prompt the user to specify which  project a product should be added on which to add a product 
* helper will allow for a user to set/clear a default project on which to add additional projects
* helper will set default project tab in cart modal 

Multi-project cart modal, i.e. the cart
* cart modal will group products by project in project tabs 
  * project tabs will be removable via an [x] in the top right
* each project tab  will have a "financial header"
  * will display present monthly cost, estimated cart monthly cost, any alerts that might occur, any other financial information relating to the project and cart
* products in a project tab will be listed in a table underneath the "financial header" in a table
  * table will  make accommodations to display estimated and configured prices (for those items requiring configuration)
  * table will include configure (when available) and remove (always) product "action" icons, complete vs incomplete configured products will be indicated using layered icons
  * selecting configure will transition cart modal to the product configuration view, ordering cannot be performed until all items have been configured
  *  Project tab will display totals for columns when available 

Please feel free to add suggestions or grievances. The right to revise this is reserved as the work evolves.

**Comment by stackus** [comment]
Good news is that pricing is static for the time being. No amount of configuration will change what a product will be listed at in the marketplace or cart. That's one concern down.

**Comment by AllenBW** [comment]
Friday update:
* products added to either origin state (specified by project.details), specified, or default project when using either the compare or adding projects via marketplace

TODO: 
* build the cart 
* mechanism to reset default project
