### ISSUE TITLE
Demo Extension : Create Provider and Products

### ISSUE THREAD

**Issue by stackus** [boozallen/projectjellyfish#1077]
The demo extension will need at least one provider and several product types to show off the provisioning abilities.

- [x] Create one (or more) provider that can be added
- [x] Create several (or more) product types with distinct product and order question sets
- [x] Include service details overrides for some product types

Belongs to #955

**Comment by mafernando** [comment]
Closed by https://github.com/projectjellyfish/jellyfish-demo/pull/8.
