### ISSUE TITLE
Demo Extension : Federal dataset

### ISSUE THREAD

**Issue by stackus** [boozallen/projectjellyfish#1098]
Datasets should include

    Projects
        Project questions should make sense
    Products
    Product Categories
    Orders
    Services
    Wizard Questions
    In general
        Use variable length Lorem ipsum text for descriptions. Something like one to 5 paragraphs should do.
        Tags for things should make sense
        Alerts for various objects
            Alerts should make sense and should not be assigned arbitrarily.
        Answers for various objects
            Answers should make sense and should not be assigned arbitrarily.

**Comment by mafernando** [comment]
Closing this as it has fallen out of scope.
