### ISSUE TITLE
Demo Extension : Generic dataset

### ISSUE THREAD

**Issue by stackus** [boozallen/projectjellyfish#1100]
Datasets should include

    Projects
        Project questions should make sense
    Products
    Product Categories
    Orders
    Services
    Wizard Questions
    In general
        Use variable length Lorem ipsum text for descriptions. Something like one to 5 paragraphs should do.
        Tags for things should make sense
        Alerts for various objects
            Alerts should make sense and should not be assigned arbitrarily.
        Answers for various objects
            Answers should make sense and should not be assigned arbitrarily.

**Comment by mafernando** [comment]
To Do List:
- [x] Create new Rails plugin
- [ ] Add "Generic" Compnents:
  - [ ] ProviderType
  - [ ] ProductType
  - [ ] Product
  - [ ] Project?
  - [ ] Service? 
  - [ ] Provider
  - [ ] Product 
- [ ] Customize remaining products in dataset
- [ ] Strip `sample:demo` dependencies from core

**Comment by mafernando** [comment]
Closed by https://github.com/projectjellyfish/jellyfish-demo/pull/8.
