### ISSUE TITLE
Demo Extension : Provider

### ISSUE THREAD

**Issue by stackus** [boozallen/projectjellyfish#1102]
The demo extension will need at least one provider that can mock provision new products.

The provider should showcase custom provider questions.

**Comment by mafernando** [comment]
Per the initial request:
- [x] The demo extension will need at least one provider that can mock provision new products. See [here](https://github.com/mafernando/jellyfish-demo/blob/feature/1100-generic-dataset/app/models/jellyfish_demo/registered_provider/demo.rb) for `RegisteredProvider` and [here](https://github.com/mafernando/jellyfish-demo/blob/feature/1100-generic-dataset/app/models/jellyfish_demo/provider/demo.rb) for `Provider`.
- [x] The provider should showcase custom provider questions. See [here](https://github.com/mafernando/jellyfish-demo/blob/feature/1100-generic-dataset/app/models/jellyfish_demo/registered_provider/demo.rb#L28-L30) for custom provider questions.

**Comment by mafernando** [comment]
Closed by https://github.com/projectjellyfish/jellyfish-demo/pull/8
