### ISSUE TITLE
Unable to save changes to Product Categories

### ISSUE THREAD

**Issue by AnkyrinRepeat** [boozallen/projectjellyfish#1122]
Trying to save any changes to Product Categories gets the error 'Missing parameters tag_list'.

**Comment by mafernando** [comment]
Looks like this is an issue in the Javascript, the call never makes it to the Rails API endpoint for product category create.

**Comment by mafernando** [comment]
Both create and edit for product categories are not saving tag lists:

![image](https://cloud.githubusercontent.com/assets/9356425/14678802/df1c4c06-06dc-11e6-9485-797ddd124428.png)

![image](https://cloud.githubusercontent.com/assets/9356425/14678821/eccd683a-06dc-11e6-8c01-7a4e79f76c14.png)

**Comment by mafernando** [comment]
Note: Saving tags on create a new product works as expected, should be able to recycle or reference that in figuring out why product categories are validating incorrectly.

**Comment by mafernando** [comment]
Turns out it was an issue with apipie and not the front end. Thanks @stackus for helping me sort that out.

**Comment by mafernando** [comment]
Addressed by commit https://github.com/boozallen/projectjellyfish/pull/1142/commits/f3a01eed7c27380d5c7b9c184e05354ce48e6a3b

**Comment by mafernando** [comment]
Closed by https://github.com/boozallen/projectjellyfish/pull/1142
