### ISSUE TITLE
Setup: Errors on Docker Setup

### ISSUE THREAD

**Issue by chunzales** [boozallen/projectjellyfish#1127]
Attempting to setup JF on Docker. When I attempt to setup the database ( docker-compose run web rake db:migrate && rake db:seed && rake sample:demo ), I get the following error:

rake aborted!
cannot load such file -- bundler/setup
/Documents/projectjellyfish-master/config/boot.rb:3:in '&lt;top (required)&gt;'
/Documents/projectjellyfish-master/config/application.rb:1:in '&lt;top (required)&gt;'
/Documents/projectjellyfish-master/Rakefile:5:in '&lt;top (required)&gt;'
(See full trace by running task with --trace)

I can't tell exactly how far it got, but it appeared to do some of the migration.

**Comment by mafernando** [comment]
@chunzales - I believe this is working now, can you please try deploying again from the latest `Dockerfile` and `docker-compose.yml`?
