### ISSUE TITLE
fix rubocop errors

### ISSUE THREAD

**Issue by chriskacerguis** [boozallen/projectjellyfish#1128]
Seems like lots of Rubocop errors have shown up.  Please address.

**Comment by mafernando** [comment]
Bumping the Ruby version to 2.3.0 introduced some new Rubocop criteria which fails on the current `master` branch.

Moreover, some of these issues can't be readily autocorrected by Rubocop:

```
app/models/permissions.rb:1:1: E: class definition in method body
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
class Permissions
^^^^^
app/models/permissions.rb:2:23: E: unexpected token tCOMMA
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
  def initialize(user:, object:)
```

The suggestions I've encountered point to setting the `TargetRubyVersion` to 2.3 in the `rubocop.yml` so the Ruby 2.3 Rubocop parser gets invoked. This adds some additional criteria and issues, but those seem straightforward to correct now.  

See https://github.com/bbatsov/rubocop/issues/2670 for additional context.

**Comment by mafernando** [comment]
Working Branch: https://github.com/mafernando/api/tree/feature/1128-fix-rubocop-issues
