### ISSUE TITLE
Invalid credentials after configuring the docker containers

### ISSUE THREAD

**Issue by raghav-vk** [boozallen/projectjellyfish#1135]
I was able to run the docker … the container seems to be up and running fine.

docker-compose up                                    
Starting api_db_1
Recreating api_web_1
Attaching to api_db_1, api_web_1
db_1  | LOG:  database system was shut down at 2016-04-08 20:03:24 UTC
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  database system is ready to accept connections
db_1  | LOG:  autovacuum launcher started
web_1 | => Booting Puma
web_1 | => Rails 4.2.3 application starting in docker on http://0.0.0.0:3000
web_1 | => Run `rails server -h` for more startup options
web_1 | => Ctrl-C to shutdown server
web_1 | [1] Puma starting in cluster mode...
web_1 | [1] * Version 3.2.0 (ruby 2.3.0-p0), codename: Spring Is A Heliocentric Viewpoint
web_1 | [1] * Min threads: 8, max threads: 16
web_1 | [1] * Environment: docker
web_1 | [1] * Process workers: 3
web_1 | [1] * Preloading application
web_1 | [1] * Listening on tcp://0.0.0.0:3000
web_1 | [1] Use Ctrl-C to stop
web_1 | [1] - Worker 0 (pid: 10) booted, phase: 0
web_1 | [1] - Worker 1 (pid: 18) booted, phase: 0
web_1 | [1] - Worker 2 (pid: 26) booted, phase: 0
db_1  | ERROR:  database "postgres" already exists
db_1  | STATEMENT:  CREATE DATABASE "postgres" ENCODING = 'unicode'

I see this error when running the seed data:

C02P5397G3QP% docker-compose run web rake db:seed    
DEPRECATION WARNING: You are passing an instance of ActiveRecord::Base to `exists?`. Please pass the id of the object by calling `.id`. (called from <top (required)> at /api/db/seeds/theme.rb:2)

I cannot login with the credentials 

Kacerguis, Christopher [USA]: (3:06 PM)
admin@projectjellyfish.org
Kacerguis, Christopher [USA]: (3:06 PM)
projectjellyfish
 
Any assistance with this would be helpful.
<img width="1437" alt="screen shot 2016-04-11 at 8 28 27 am" src="https://cloud.githubusercontent.com/assets/13239172/14426866/8d8f83a4-ffbf-11e5-8267-987d005252b2.png">

**Comment by mafernando** [comment]
Please try password `jellyfish` instead with the `admin@projectjellyfish.org` username.
