### ISSUE TITLE
Fix 'rake sample:demo'

### ISSUE THREAD

**Issue by railsmith** [boozallen/projectjellyfish#1136]
'rake sample:demo' from api repo fails with the following error.

    NoMethodError: undefined method `product_id=' for #<Null::Service:0x00000009dd40b0>
    Did you mean?  product=
    /home/jellyfish/.rvm/gems/ruby-2.3.0@jellyfish/gems/activemodel-4.2.3/lib/active_model    /attribute_methods.rb:433:in `method_missing'
    /home/jellyfish/Documents/api/lib/tasks/sample.rake:94:in `block (5 levels) in <top (required)>'
    /home/jellyfish/Documents/api/lib/tasks/sample.rake:91:in `tap'
    /home/jellyfish/Documents/api/lib/tasks/sample.rake:91:in `block (4 levels) in <top (required)>'
     /home/jellyfish/Documents/api/lib/tasks/sample.rake:85:in `map'
    /home/jellyfish/Documents/api/lib/tasks/sample.rake:85:in `block (3 levels) in <top (required)>'
    /home/jellyfish/Documents/api/lib/tasks/sample.rake:5:in `block in sample_data'
    /home/jellyfish/Documents/api/lib/tasks/sample.rake:5:in `each'
    /home/jellyfish/Documents/api/lib/tasks/sample.rake:5:in `sample_data'
    /home/jellyfish/Documents/api/lib/tasks/sample.rake:79:in `block (2 levels) in <top (required)>'
    /home/jellyfish/.rvm/gems/ruby-2.3.0@jellyfish/bin/ruby_executable_hooks:15:in `eval'
    /home/jellyfish/.rvm/gems/ruby-2.3.0@jellyfish/bin/ruby_executable_hooks:15:in `<main>'
    Tasks: TOP => sample:demo
    (See full trace by running task with --trace)

**Comment by watkinsc** [comment]
Have you run the following rake tasks before attempting 'rake sample:demo'?
```
rake db:setup
rake db:seed
```

**Comment by railsmith** [comment]
I have done all that. Even the model specs were failing after you clone the repo from this url 

     git clone https://github.com/projectjellyfish/api.git. 

Is the error not reproducing for you? Am I missing something? I have managed to fix it in the meanwhile by adding these two migrations and ran `rake db:migrate` which fixed the failing model specs and the above error. 

    rails g migration RemoveColumnFromOrder product_id:integer service_id:integer
    rails g migration AddColumnToService product_id:integer order_id:integer

**Comment by chriskacerguis** [comment]
Looks like you are cloning the wrong repo, could you please give this one a try:

https://github.com/boozallen/projectjellyfish.git

Chris

**Comment by railsmith** [comment]
Tried with cloning this repo, rspec models are passing but the above error still persists.

**Comment by chriskacerguis** [comment]
@railsmith can you please cut and paste the error you are now seeing?

**Comment by railsmith** [comment]
NoMethodError: undefined method `product_id=' for #<Null::Service:0x00000009b096a0>
    Did you mean?  product=
    /home/jellyfish/.rvm/gems/ruby-2.3.0@jellyfish/gems/activemodel-4.2.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
    /home/jellyfish/Documents/projectjellyfish/lib/tasks/sample.rake:94:in `block (5 levels) in <top (required)>'
    /home/jellyfish/Documents/projectjellyfish/lib/tasks/sample.rake:91:in `tap'
    /home/jellyfish/Documents/projectjellyfish/lib/tasks/sample.rake:91:in `block (4 levels) in <top (required)>'
    /home/jellyfish/Documents/projectjellyfish/lib/tasks/sample.rake:85:in `map'
    /home/jellyfish/Documents/projectjellyfish/lib/tasks/sample.rake:85:in `block (3 levels) in <top (required)>'
    /home/jellyfish/Documents/projectjellyfish/lib/tasks/sample.rake:5:in `block in sample_data'
    /home/jellyfish/Documents/projectjellyfish/lib/tasks/sample.rake:5:in `each'
    /home/jellyfish/Documents/projectjellyfish/lib/tasks/sample.rake:5:in `sample_data'
    /home/jellyfish/Documents/projectjellyfish/lib/tasks/sample.rake:79:in `block (2 levels) in <top (required)>'
    /home/jellyfish/.rvm/gems/ruby-2.3.0@jellyfish/bin/ruby_executable_hooks:15:in `eval'
    /home/jellyfish/.rvm/gems/ruby-2.3.0@jellyfish/bin/ruby_executable_hooks:15:in `<main>'
    Tasks: TOP => sample:demo

Running my migrations fixes the issue.

**Comment by chriskacerguis** [comment]
Yes, did you run first?
```
rake db:setup
rake db:seed
```

**Comment by railsmith** [comment]
Yes, I did ran those first.

**Comment by chriskacerguis** [comment]
@mafernando any thoughts on this?

**Comment by chriskacerguis** [comment]
Closing this ticket.  This is no longer part of the work build process in develop, and we'll be promoting in a day or so.
