### ISSUE TITLE
Issue Running docker-compose up

### ISSUE THREAD

**Issue by nickbisson** [boozallen/projectjellyfish#1137]
I'm trying to install PJF on Win7 via docker. Installation starts with docker-compose up. No issues until step 16 where it stops at this point:

![image](https://cloud.githubusercontent.com/assets/17887547/14534685/3a071686-0238-11e6-8eaa-1926631c3d47.png)

Any advice?

**Comment by watkinsc** [comment]
> Your Ruby version is 2.2.3, but your Gemfile specified 2.3.0

It would appear something (maybe your Dockerfile or .ruby-version) is specifying ruby 2.2.3, and the Gemfile specifies 2.3.0.

Ensure you've cloned the latest from https://github.com/boozallen/projectjellyfish.git 
Once you've done that, try 'docker-compose up' and see if the issue persists.

**Comment by chriskacerguis** [comment]
I'm wondering if you have an older version of the code.  Can you pull the latest?

**Comment by mafernando** [comment]
Hi @nickbisson, I'm looking into this issue and will get back to you. 

Can you please provide the steps you are following to deploy JF?

**Comment by nickbisson** [comment]
Hi @mafernando . Looks like I was using an older version of the repo. Downloading the latest master allows me to install, however there is a new issue... opening a new issue.
