### ISSUE TITLE
Docker Compose ERROR:  yaml.scanner.ScannerError

### ISSUE THREAD

**Issue by matthewtisdale** [boozallen/projectjellyfish#1145]
I am new to Docker and was trying to follow the instructions to get Jellyfish up and running using Docker. Docker and Docker-compose seem to have installed correctly but I am getting the following error when running docker-compose up:
 
ERROR:  yaml.scanner.ScannerError: mapping values are not allowed here in “./docker-compose.yml” 

I have a virtual machine with Red Hat Enterprise Linux Server 7.2 (3.10.0-327.13.1.el7.x86_64)

**Comment by chriskacerguis** [comment]
Hi @matthewtisdale 

I wasn't able to reproduce the error you pointed out.  Could you please let me know the install procedure you followed?

Thanks!

Chris

**Comment by matthewtisdale** [comment]
Chris,

I was just double checking the Dockerfile and docker-compose.yml files.  They looked like they were recently updated and it appears to be working now.  The original docker-compose file I was using was quite a bit larger.  I am getting the following error, but its getting a lot further now:

ERROR:  Service ‘web’ failed to build: The command ‘/bin/sh -c bundle install –without development test’ returned a non-zero code: 18

Thanks,
Matt

**Comment by matthewtisdale** [comment]
It looks like its failing on the json 1.8.1 install:


[mstisdal@sandboxvm projectjellyfish-2.0.0]$ docker-compose up

Building web

Step 1 : FROM ruby:2.3.0

 ---> 7ca70eb2dfea

Step 2 : RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

 ---> Using cache

 ---> 9228edb6fe86

Step 3 : RUN curl -sL https://deb.nodesource.com/setup_4.x | bash -

 ---> Using cache

 ---> bb52e5881444

Step 4 : RUN apt-get install -y nodejs

 ---> Using cache

 ---> 09232bbc890f

Step 5 : RUN mkdir /api

 ---> Using cache

 ---> 2a8184ed8435

Step 6 : WORKDIR /api

 ---> Using cache

 ---> ce4c879c70a7

Step 7 : ENV RACK_ENV docker

 ---> Using cache

 ---> 04d2ebc70919

Step 8 : ENV RAILS_ENV docker

 ---> Using cache

 ---> 91c75d6102e7

Step 9 : ENV DEVISE_SECRET_KEY 978e423d107dc2277f2987787a2f8ccd5ee0dcedf40f05f0188d732516a79559a7434feb56f35f31376f1b12325ac28ea540c8387fba83cb070e43af271ff9e9

 ---> Using cache

 ---> 4bfa8f0b8ddc

Step 10 : ENV SECRET_KEY_BASE c7a71de57183e6e8aefede7737332c6283ce85a061a779fd761eac14c011255b6fd151d8cb3dd7403404b0f248f01bf4cfb97a17ec72b9ff3c5d1bd1ca3d72b2

 ---> Using cache

 ---> 145ffc4434b6

Step 11 : COPY Gemfile /api/

 ---> Using cache

 ---> edc593b4eb70

Step 12 : COPY Gemfile.lock /api/

 ---> Using cache

 ---> a786f1064893

Step 13 : COPY . /api/

 ---> Using cache

 ---> f105d4023173

Step 14 : RUN npm install -g gulp bower

 ---> Using cache

 ---> 8a27ca425784

Step 15 : RUN npm install gulp bower

 ---> Using cache

 ---> d83f6bbb03b8

Step 16 : RUN bundle install --without development test

 ---> Running in 47fe054d4364

Fetching gem metadata from https://rubygems.org/.........

Fetching version metadata from https://rubygems.org/...

Fetching dependency metadata from https://rubygems.org/..

Installing rake 10.4.2

Installing i18n 0.7.0

Installing json 1.8.1 with native extensions


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.


    current directory: /usr/local/bundle/gems/json-1.8.1/ext/json/ext/generator

/usr/local/bin/ruby -r ./siteconf20160420-5-1xuqxju.rb extconf.rb

creating Makefile


current directory: /usr/local/bundle/gems/json-1.8.1/ext/json/ext/generator

make "DESTDIR=" clean


current directory: /usr/local/bundle/gems/json-1.8.1/ext/json/ext/generator

make "DESTDIR="

compiling generator.c

In file included from generator.c:1:0:

../fbuffer/fbuffer.h: In function 'fbuffer_to_s':

../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given

     VALUE result = rb_str_new(FBUFFER_PAIR(fb));

                                               ^

../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast

     VALUE result = rb_str_new(FBUFFER_PAIR(fb));

                    ^

Makefile:238: recipe for target 'generator.o' failed

make: *** [generator.o] Error 1


make failed, exit code 2


Gem files will remain installed in /usr/local/bundle/gems/json-1.8.1 for inspection.

Results logged to /usr/local/bundle/extensions/x86_64-linux/2.3.0-static/json-1.8.1/gem_make.out

Installing minitest 5.5.0

Installing thread_safe 0.3.4

Installing builder 3.2.2

Installing erubis 2.7.0

Installing rack 1.5.2

Installing mime-types 2.4.3

Installing arel 5.0.1.20140414130214

Using bundler 1.11.2

Installing thor 0.19.1

Installing hike 1.2.3

Installing multi_json 1.10.1

Installing tilt 1.4.1

Installing ice_nine 0.11.1

Installing bcrypt 3.1.9 with native extensions

Installing chronic 0.10.2

Installing daemons 1.1.9

Installing orm_adapter 0.5.0

Installing equalizer 0.0.9

Installing highline 1.6.21

Installing netrc 0.10.2

Installing pg 0.17.1 with native extensions

Installing rack-cors 0.3.0

Installing will_paginate 3.0.7

An error occurred while installing json (1.8.1), and Bundler cannot continue.

Make sure that `gem install json -v '1.8.1'` succeeds before bundling.

ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install --without development test' returned a non-zero code: 5

________________________________
From: Tisdale, Matthew [USA]
Sent: Wednesday, April 20, 2016 9:03 AM
To: boozallen/projectjellyfish
Subject: RE: [External] Re: [boozallen/projectjellyfish] Docker Compose ERROR: yaml.scanner.ScannerError (#1145)

Chris,

I was just double checking the Dockerfile and docker-compose.yml files.  They looked like they were recently updated and it appears to be working now.  The original docker-compose file I was using was quite a bit larger.  I am getting the following error, but its getting a lot further now:

ERROR:  Service ‘web’ failed to build: The command ‘/bin/sh -c bundle install –without development test’ returned a non-zero code: 18

Thanks,
Matt

**Comment by chriskacerguis** [comment]
Hmmm...looking into that.

**Comment by chriskacerguis** [comment]
Hi @matthewtisdale I can't produce that error either, are you using the develop or master branch?
