### ISSUE TITLE
Is the new build process ready for production?

### ISSUE THREAD

**Issue by railsmith** [boozallen/projectjellyfish#1158]
I see that the UX is being moved to rails assets but is this new build process ready for production yet? I have hosted the Jellyfish application using nginx + passenger in production environment. 

I am not able to see the login page and there are no errors in the firebug console too. All the assets are loaded correctly. No errors in `/var/log/nginx/error.log` either.

### Expected Behavior

![screenshot from 2016-04-22 14-49-55](https://cloud.githubusercontent.com/assets/5390273/14737482/dd4ce232-0899-11e6-96f9-930538828020.png)

### Current Behavior

![screenshot from 2016-04-22 14-50-02](https://cloud.githubusercontent.com/assets/5390273/14737493/f3606972-0899-11e6-8be4-dc450976a209.png)

### Steps to Reproduce (for bugs)

1. Set secret_key_base for production in `secrets.yml`
2. `RAILS_ENV=production rake assets:precompile`
3.  Add touch index.css.erb and index.js.erb to `app/assets/views/site` path.
4.  Add `index` method to `skip_before_action :verify_authenticity_token, if: :json_request?, only: [:create, :index, :acs]` in `application_controller`.
5. Give the necessary permissions for nginx to serve static files.

### Context
I am hosting the Jellyfish application using nginx + passenger in production environment.

### Your Environment

* Version used: Jellyfish develop branch version
* Browser Name and version: Firefox 38.7.0
* Operating System and version (desktop): Cent OS 7

**Comment by chriskacerguis** [comment]
Hello,

It looks like you are using the develop branch, and I would not suggest running that in production.  can you please try using the stable master branch?
