### ISSUE TITLE
docker-compose up failing, Dockerfile out of date

### ISSUE THREAD

**Issue by watkinsc** [boozallen/projectjellyfish#1160]
### Expected Behavior

Upon cloning boozallen/projectjellyfish, you should be able to run `docker-compose up` from a Docker terminal to create and start both a web and db container.

### Current Behavior

Running `docker-compose up` will create db container, and attempt to create web container. Web container will fail on NPM install (Step 17).

### Possible Solution

As per #1147 the build process has changed to no longer use npm and gulp, in favor of bundle and rake tasks. The Dockerfile/docker-compse.yml should be updated to reflect this change.

### Steps to Reproduce (for bugs)

1. Clone boozallen/projectjellyfish
2. Open a docker terminal and navigate to repository
3. From the newly cloned repository, run `docker-compose up`

### Context

With your release of v4.0.0, you are currently unable to run Project Jellyfish as a Docker container. 

### Your Environment

* Version used: v4.0.0 (#1159)
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Mac OSX (Desktop)

**Comment by chriskacerguis** [comment]
Looking into this.

**Comment by chriskacerguis** [comment]
Looks like the builds were failing.  should be working now.
