### ISSUE TITLE
Add AD Support to JF

### ISSUE THREAD

**Issue by mafernando** [boozallen/projectjellyfish#1162]
Add ActiveDirectory Support to Project Jellyfish.

### Expected Behavior
Users can log into Project Jellyfish through ActiveDirectory.

Per Chris Hample:

```
Integration w/AD really through a 3-rd party procider like a forgerock
...
new users will only be right now through some AD piece
...
from an identity standpoint development[sic] is connection with existing AD.  
will have CAK card too.  
some of that can be built specifically in development[sic] itself, but integration with identity provider is key and connectivity to AD groups
```

### Current Behavior
Users currently login to Project Jellyfish using an existing `admin` user seeded when the application is deployed or through a user account created by an existing admin user.

### Possible Solution
TBD - looking at solutions to find what is appropriate here. 

### Steps to Reproduce (for bugs)
n/a

### Context
A Project Jellyfish deployment may need to function in environments where users authenticate with AD to leverage account access across multiple services. 

### Your Environment

* ForgeRock Version: TBD
* Version used: TBD
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by chriskacerguis** [comment]
AD is LDAP, which a ticket for that already exists.  Also a CAC (Common Access Card) would be a SAML (ticket for that exists too). So I think this ticket is not needed.
