### ISSUE TITLE
Move login methods back into core

### ISSUE THREAD

**Issue by chriskacerguis** [boozallen/projectjellyfish#952]
We want to move the login methods (SAML, LDAP/AD, Internal DB) back into core, and no longer in a module.

**Comment by OBCENEIKON** [comment]
Updated the backend to use the Omniauth-Identity module. The front end needs to be able to send the authentication credentials to /api/v1/staff/auth/identity.
The fork is located at https://github.com/OBCENEIKON/api/tree/development/Move_login_methods_back_into_core-952

**Comment by AllenBW** [comment]
Pausing work, issue future under evaluation by @stackus

**Comment by chriskacerguis** [comment]
Closing this ticket, breaking up into smaller tickets
