### ISSUE TITLE
The Jellyfish demo content should be made into an extension

### ISSUE THREAD

**Issue by chriskacerguis** [boozallen/projectjellyfish#955]
With the recent changes to Jellyfish it is no longer a good idea to install the demo data into the application by default. In production environments this will create some references that administrators would need to clean out.

* Create a repository for the demo `jellyfish-demo-data`
* Add `jellyfish-demo-data` to the Gemfile in a `:development` group
* Change database.yml so that development and production do not share a database
* Move demo load task into new gem
* Only mock provisioning

Core will need to be able to function 100% after everything demo has been extracted. This includes but is not limited to, initial accounts are setup, settings exist with default values and all screens and endpoints function with less or no data setup.

- [x] #1077 : Create Provider & Products
- [x] #1078 : Create datasets

**Comment by mafernando** [comment]
Bringing this into the current spring (2.0) since its a superset of the demo dataset issues.

**Comment by mafernando** [comment]
Closed by https://github.com/projectjellyfish/jellyfish-demo/pull/8/
