### ISSUE TITLE
Create "/admin" landing page

### ISSUE THREAD

**Issue by chriskacerguis** [boozallen/projectjellyfish#961]
Create an Admin landing page. We've already moved the list of Projects out of the sidebar in the ux-refresh, and onto its own My Projects landing page, and we'd like to remain consistent.

**Comment by sonejah21** [comment]
@chriskacerguis @stackus Would this be the page that opens when you click on Admin in the sidebar? Do we know what content (i.e. dashboard) and/or functionality (actions) we want to see in this page yet? I think this ticket should be a part of the larger conversation of how we want all of our pages to look and function. Please advise.

**Comment by stackus** [comment]
I think you're right that we should discuss this. Another way to think of this as is an "admin dashboard".

**Comment by sonejah21** [comment]
As for the Admin landing page contents, I envision it containing widgets that display information about the Alerts, Groups, Roles, Settings, Users & Providers (aka: the nested items under "Admin" in the sidebar). Is that what we have in mind? Saying it is an "admin dashboard" may be confused with the initial Dashboard view when logged in as an Admin, so we'll have to be careful about wording here!

**Comment by chriskacerguis** [comment]
Going to close this one.   I think that this isn't needed for the time being.
